services:
  postgres:
    image: postgres:14 
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: todoList
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    hostname: redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379