database:
  postgresql:
    database: todoList
    username: admin
    password: admin
    host: localhost
    port: 5432
    adabter: postgresql
    time_zone: Asia/Tehran
    charset: utf8mb4
    
  mysql:
   
logger:
  max_age: 720h
  max_size: 20MB
  filename_pattern: "%Y-%m-%dT%H:%M"
  rotation_time: "24h"
  internal_path: "./log/data"

server:
  host: localhost
  port: 8089

redis:
  server: localhost
  password: ""
  db: 0
  port: 6379